# Generated by Django 3.2 on 2022-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220515_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Industry',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Design', 'Design'), ('Healthcare', 'Healthcare'), ('Transport', 'Transport'), ('Insuarance', 'Insuarance')], default='', max_length=21),
        ),
    ]
