# Generated by Django 3.2 on 2022-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_shop_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='county',
            field=models.CharField(blank=True, choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana-River', 'Tana-River'), ('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Murang’a', 'Murang’a'), ('Kiambu', 'Kiambu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin-Gishu', 'Uasin-Gishu'), ('Laikipia', 'Laikipia'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('HomaBay', 'HomaBay'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Taita-Taveta', 'Taita-Taveta'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Turkana', 'Turkana'), ('West-Pokot', 'West-Pokot'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Migori', 'Migori'), ('Nakuru', 'Nakuru')], default='', max_length=100, null=True),
        ),
    ]
