# Generated by Django 3.2 on 2022-10-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_client_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Industry',
            field=models.CharField(choices=[('Real Estate', 'Real Estate'), ('Technology', 'Technology'), ('Botique', 'Botique'), ('Second Hand Items', 'Second Hand Items'), ('Transport', 'Transport'), ('Insuarance', 'Insuarance')], default='', max_length=21),
        ),
    ]
