# Generated by Django 3.2 on 2022-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_about_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('aboutus', models.TextField(blank=True, max_length=500)),
                ('aboutimage', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('story', models.TextField(blank=True, max_length=1500)),
                ('storyimage', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('team', models.TextField(blank=True, max_length=1500)),
                ('teamimage', models.ImageField(blank=True, upload_to='post/%Y/%m/%d')),
                ('whyus', models.TextField(blank=True, max_length=1500)),
                ('whyusimage', models.URLField(blank=True, max_length=350)),
            ],
        ),
    ]
