# Generated by Django 3.2 on 2022-10-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentAddress',
            fields=[
                ('building', models.CharField(db_index=True, max_length=30)),
                ('description', models.CharField(db_index=True, max_length=1000)),
                ('landmark', models.CharField(db_index=True, default='', max_length=30)),
                ('door_no', models.CharField(db_index=True, default='', max_length=25)),
                ('floor_no', models.CharField(db_index=True, default='', max_length=25)),
                ('uniqueadress', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', django_google_maps.fields.AddressField(max_length=200, null=True)),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana-River', 'Tana-River'), ('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Murang’a', 'Murang’a'), ('Kiambu', 'Kiambu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin-Gishu', 'Uasin-Gishu'), ('Laikipia', 'Laikipia'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('HomaBay', 'HomaBay'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Taita-Taveta', 'Taita-Taveta'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Turkana', 'Turkana'), ('West-Pokot', 'West-Pokot'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Migori', 'Migori'), ('Nakuru', 'Nakuru')], db_index=True, max_length=500)),
                ('lat', models.FloatField(default='-1.2345', max_length=20, null=True)),
                ('lon', models.FloatField(default='36.4567', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('slug', models.SlugField(default='1')),
                ('businessname', models.CharField(db_index=True, max_length=27)),
                ('building', models.CharField(db_index=True, max_length=18)),
                ('landmark', models.CharField(db_index=True, default='', max_length=20)),
                ('description', models.TextField(db_index=True, default='write the description here...', max_length=800)),
                ('door_no', models.CharField(db_index=True, default='', max_length=10)),
                ('contact', models.CharField(db_index=True, default='', max_length=16)),
                ('floor_no', models.CharField(db_index=True, default='', max_length=10)),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana-River', 'Tana-River'), ('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Murang’a', 'Murang’a'), ('Kiambu', 'Kiambu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin-Gishu', 'Uasin-Gishu'), ('Laikipia', 'Laikipia'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('HomaBay', 'HomaBay'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Taita-Taveta', 'Taita-Taveta'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Turkana', 'Turkana'), ('West-Pokot', 'West-Pokot'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Migori', 'Migori'), ('Nakuru', 'Nakuru')], db_index=True, max_length=30)),
                ('uniqueadress', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='business/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='business/%Y/%m/%d')),
                ('lat', models.FloatField(default='-1.2345', max_length=20)),
                ('lon', models.FloatField(default='36.5432', max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'index_together': {('uniqueadress', 'slug')},
            },
        ),
    ]
