# Generated by Django 3.2 on 2022-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaddress',
            old_name='description',
            new_name='street',
        ),
    ]
