# Generated by Django 3.2 on 2022-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0002_rename_description_businessaddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentaddress',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
