# Generated by Django 3.2 on 2022-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=700)),
                ('image', models.URLField(blank=True, max_length=350)),
                ('title1', models.CharField(max_length=500)),
                ('content1', models.CharField(blank=True, max_length=700)),
                ('image1', models.URLField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True, max_length=350)),
                ('imagedescription', models.CharField(blank=True, max_length=500)),
                ('image1', models.URLField(blank=True, max_length=350)),
                ('imagedescription1', models.CharField(blank=True, max_length=500)),
                ('post1', models.CharField(blank=True, max_length=500)),
                ('image2', models.URLField(blank=True, max_length=350)),
                ('imagedescription2', models.CharField(blank=True, max_length=500)),
                ('post2', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
